insert into public.word_list_collections (
  id,
  slug,
  name,
  name_cy,
  description,
  description_cy,
  type,
  source_language,
  target_language,
  curriculum_key_stage,
  curriculum_area,
  owner_type,
  owner_id,
  order_index,
  is_active
) values (
  'practice',
  'practice',
  'Practice',
  'Ymarfer',
  'Useful Welsh spelling practice organised by topic.',
  null,
  'spelio_core',
  'en',
  'cy',
  null,
  null,
  'spelio',
  null,
  3,
  false
) on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  name_cy = excluded.name_cy,
  description = excluded.description,
  description_cy = excluded.description_cy,
  type = excluded.type,
  source_language = excluded.source_language,
  target_language = excluded.target_language,
  curriculum_key_stage = excluded.curriculum_key_stage,
  curriculum_area = excluded.curriculum_area,
  owner_type = excluded.owner_type,
  owner_id = excluded.owner_id,
  order_index = excluded.order_index,
  is_active = excluded.is_active;
