insert into public.word_lists (
  id,
  slug,
  collection_id,
  name,
  name_cy,
  description,
  description_cy,
  language,
  source_language,
  target_language,
  dialect,
  stage_id,
  focus_category_id,
  difficulty,
  order_index,
  next_list_id,
  is_active,
  list_type,
  hidden_from_main_catalogue,
  primer_content
) values (
  'practice_most_common_food_and_drink',
  'most-common-food-and-drink',
  'practice',
  'Most Common Food & Drink',
  null,
  'Practise the Welsh names of common food and drink used in everyday conversation.',
  null,
  'Welsh',
  'en',
  'cy',
  'Mixed',
  'core',
  'topic-vocabulary',
  1,
  2,
  null,
  true,
  'main',
  false,
  '{
    "enabled": false,
    "titleEn": "",
    "titleCy": "",
    "bodyEn": "",
    "bodyCy": "",
    "soundItems": []
  }'::jsonb
) on conflict (id) do update set
  slug = excluded.slug,
  collection_id = excluded.collection_id,
  name = excluded.name,
  name_cy = excluded.name_cy,
  description = excluded.description,
  description_cy = excluded.description_cy,
  language = excluded.language,
  source_language = excluded.source_language,
  target_language = excluded.target_language,
  dialect = excluded.dialect,
  stage_id = excluded.stage_id,
  focus_category_id = excluded.focus_category_id,
  difficulty = excluded.difficulty,
  order_index = excluded.order_index,
  next_list_id = excluded.next_list_id,
  is_active = excluded.is_active,
  list_type = excluded.list_type,
  hidden_from_main_catalogue = excluded.hidden_from_main_catalogue,
  primer_content = excluded.primer_content;

insert into public.words (
  id,
  list_id,
  english_prompt,
  welsh_answer,
  accepted_alternatives,
  audio_url,
  audio_status,
  notes,
  usage_note,
  dialect,
  dialect_note,
  variant_group_id,
  order_index,
  difficulty
) values
  ('practice_most_common_food_and_drink_001', 'practice_most_common_food_and_drink', 'Water', 'dŵr', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 1, 1),
  ('practice_most_common_food_and_drink_002', 'practice_most_common_food_and_drink', 'Tea', 'te', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 2, 1),
  ('practice_most_common_food_and_drink_003', 'practice_most_common_food_and_drink', 'Coffee', 'coffi', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 3, 1),
  ('practice_most_common_food_and_drink_004', 'practice_most_common_food_and_drink', 'Milk', 'llaeth', '[]'::jsonb, '', 'missing', '', '', 'South Wales / Standard', '', 'milk', 4, 1),
  ('practice_most_common_food_and_drink_005', 'practice_most_common_food_and_drink', 'Milk', 'llefrith', '[]'::jsonb, '', 'missing', '', '', 'North Wales', '', 'milk', 5, 1),
  ('practice_most_common_food_and_drink_006', 'practice_most_common_food_and_drink', 'Bread', 'bara', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 6, 1),
  ('practice_most_common_food_and_drink_007', 'practice_most_common_food_and_drink', 'Cheese', 'caws', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 7, 1),
  ('practice_most_common_food_and_drink_008', 'practice_most_common_food_and_drink', 'Butter', 'menyn', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 8, 1),
  ('practice_most_common_food_and_drink_009', 'practice_most_common_food_and_drink', 'Meat', 'cig', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 9, 1),
  ('practice_most_common_food_and_drink_010', 'practice_most_common_food_and_drink', 'Chicken', 'cyw iâr', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 10, 1),
  ('practice_most_common_food_and_drink_011', 'practice_most_common_food_and_drink', 'Sugar', 'siwgr', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 11, 1)
on conflict (id) do update set
  list_id = excluded.list_id,
  english_prompt = excluded.english_prompt,
  welsh_answer = excluded.welsh_answer,
  accepted_alternatives = excluded.accepted_alternatives,
  notes = excluded.notes,
  usage_note = excluded.usage_note,
  dialect = excluded.dialect,
  dialect_note = excluded.dialect_note,
  variant_group_id = excluded.variant_group_id,
  order_index = excluded.order_index,
  difficulty = excluded.difficulty;
