insert into public.word_lists (
  id,
  slug,
  collection_id,
  name,
  name_cy,
  description,
  description_cy,
  language,
  source_language,
  target_language,
  dialect,
  stage_id,
  focus_category_id,
  difficulty,
  order_index,
  next_list_id,
  is_active,
  list_type,
  hidden_from_main_catalogue,
  primer_content
) values (
  'practice_most_common_time_and_calendar',
  'most-common-time-and-calendar',
  'practice',
  'Most Common Time & Calendar',
  null,
  'Practise common Welsh words for time and dates.',
  null,
  'Welsh',
  'en',
  'cy',
  'Mixed',
  'core',
  'topic-vocabulary',
  1,
  8,
  null,
  true,
  'main',
  false,
  '{
    "enabled": false,
    "titleEn": "",
    "titleCy": "",
    "bodyEn": "",
    "bodyCy": "",
    "soundItems": []
  }'::jsonb
) on conflict (id) do update set
  slug = excluded.slug,
  collection_id = excluded.collection_id,
  name = excluded.name,
  name_cy = excluded.name_cy,
  description = excluded.description,
  description_cy = excluded.description_cy,
  language = excluded.language,
  source_language = excluded.source_language,
  target_language = excluded.target_language,
  dialect = excluded.dialect,
  stage_id = excluded.stage_id,
  focus_category_id = excluded.focus_category_id,
  difficulty = excluded.difficulty,
  order_index = excluded.order_index,
  next_list_id = excluded.next_list_id,
  is_active = excluded.is_active,
  list_type = excluded.list_type,
  hidden_from_main_catalogue = excluded.hidden_from_main_catalogue,
  primer_content = excluded.primer_content;

insert into public.words (
  id,
  list_id,
  english_prompt,
  welsh_answer,
  accepted_alternatives,
  audio_url,
  audio_status,
  notes,
  usage_note,
  dialect,
  dialect_note,
  variant_group_id,
  order_index,
  difficulty
) values
  ('practice_most_common_time_and_calendar_001', 'practice_most_common_time_and_calendar', 'Today', 'heddiw', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 1, 1),
  ('practice_most_common_time_and_calendar_002', 'practice_most_common_time_and_calendar', 'Tomorrow', 'yfory', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 2, 1),
  ('practice_most_common_time_and_calendar_003', 'practice_most_common_time_and_calendar', 'Yesterday', 'ddoe', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 3, 1),
  ('practice_most_common_time_and_calendar_004', 'practice_most_common_time_and_calendar', 'Now', 'nawr', '[]'::jsonb, '', 'missing', '', '', 'South Wales / Standard', 'North Wales commonly uses rwan.', 'now', 4, 1),
  ('practice_most_common_time_and_calendar_005', 'practice_most_common_time_and_calendar', 'Now', 'rwan', '[]'::jsonb, '', 'missing', '', '', 'North Wales', 'South/standard Welsh commonly uses nawr.', 'now', 5, 1),
  ('practice_most_common_time_and_calendar_006', 'practice_most_common_time_and_calendar', 'Day', 'dydd', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 6, 1),
  ('practice_most_common_time_and_calendar_007', 'practice_most_common_time_and_calendar', 'Week', 'wythnos', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 7, 1),
  ('practice_most_common_time_and_calendar_008', 'practice_most_common_time_and_calendar', 'Month', 'mis', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 8, 1),
  ('practice_most_common_time_and_calendar_009', 'practice_most_common_time_and_calendar', 'Year', 'blwyddyn', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 9, 1),
  ('practice_most_common_time_and_calendar_010', 'practice_most_common_time_and_calendar', 'Morning', 'bore', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 10, 1),
  ('practice_most_common_time_and_calendar_011', 'practice_most_common_time_and_calendar', 'Evening / night', 'nos', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 11, 1)
on conflict (id) do update set
  list_id = excluded.list_id,
  english_prompt = excluded.english_prompt,
  welsh_answer = excluded.welsh_answer,
  accepted_alternatives = excluded.accepted_alternatives,
  notes = excluded.notes,
  usage_note = excluded.usage_note,
  dialect = excluded.dialect,
  dialect_note = excluded.dialect_note,
  variant_group_id = excluded.variant_group_id,
  order_index = excluded.order_index,
  difficulty = excluded.difficulty;
