insert into public.word_lists (
  id,
  slug,
  collection_id,
  name,
  name_cy,
  description,
  description_cy,
  language,
  source_language,
  target_language,
  dialect,
  stage_id,
  focus_category_id,
  difficulty,
  order_index,
  next_list_id,
  is_active,
  list_type,
  hidden_from_main_catalogue,
  primer_content
) values (
  'practice_most_common_shopping',
  'most-common-shopping',
  'practice',
  'Most Common Shopping',
  null,
  'Practise common Welsh shopping words used in everyday conversation.',
  null,
  'Welsh',
  'en',
  'cy',
  'Both',
  'core',
  'topic-vocabulary',
  1,
  14,
  null,
  true,
  'main',
  false,
  '{
    "enabled": false,
    "titleEn": "",
    "titleCy": "",
    "bodyEn": "",
    "bodyCy": "",
    "soundItems": []
  }'::jsonb
) on conflict (id) do update set
  slug = excluded.slug,
  collection_id = excluded.collection_id,
  name = excluded.name,
  name_cy = excluded.name_cy,
  description = excluded.description,
  description_cy = excluded.description_cy,
  language = excluded.language,
  source_language = excluded.source_language,
  target_language = excluded.target_language,
  dialect = excluded.dialect,
  stage_id = excluded.stage_id,
  focus_category_id = excluded.focus_category_id,
  difficulty = excluded.difficulty,
  order_index = excluded.order_index,
  next_list_id = excluded.next_list_id,
  is_active = excluded.is_active,
  list_type = excluded.list_type,
  hidden_from_main_catalogue = excluded.hidden_from_main_catalogue,
  primer_content = excluded.primer_content;

insert into public.words (
  id,
  list_id,
  english_prompt,
  welsh_answer,
  accepted_alternatives,
  audio_url,
  audio_status,
  notes,
  usage_note,
  dialect,
  dialect_note,
  variant_group_id,
  order_index,
  difficulty
) values
  ('practice_most_common_shopping_001', 'practice_most_common_shopping', 'Shop', 'siop', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 1, 1),
  ('practice_most_common_shopping_002', 'practice_most_common_shopping', 'Money', 'arian', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 2, 1),
  ('practice_most_common_shopping_003', 'practice_most_common_shopping', 'Price', 'pris', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 3, 1),
  ('practice_most_common_shopping_004', 'practice_most_common_shopping', 'Customer', 'cwsmer', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 4, 1),
  ('practice_most_common_shopping_005', 'practice_most_common_shopping', 'Card', 'cerdyn', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 5, 1),
  ('practice_most_common_shopping_006', 'practice_most_common_shopping', 'Bag', 'bag', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 6, 1),
  ('practice_most_common_shopping_007', 'practice_most_common_shopping', 'Receipt', 'derbynneb', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 7, 1),
  ('practice_most_common_shopping_008', 'practice_most_common_shopping', 'Market', 'marchnad', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 8, 1),
  ('practice_most_common_shopping_009', 'practice_most_common_shopping', 'Buy', 'prynu', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 9, 1),
  ('practice_most_common_shopping_010', 'practice_most_common_shopping', 'Sell', 'gwerthu', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 10, 1)
on conflict (id) do update set
  list_id = excluded.list_id,
  english_prompt = excluded.english_prompt,
  welsh_answer = excluded.welsh_answer,
  accepted_alternatives = excluded.accepted_alternatives,
  notes = excluded.notes,
  usage_note = excluded.usage_note,
  dialect = excluded.dialect,
  dialect_note = excluded.dialect_note,
  variant_group_id = excluded.variant_group_id,
  order_index = excluded.order_index,
  difficulty = excluded.difficulty;
