insert into public.word_lists (
  id,
  slug,
  collection_id,
  name,
  name_cy,
  description,
  description_cy,
  language,
  source_language,
  target_language,
  dialect,
  stage_id,
  focus_category_id,
  difficulty,
  order_index,
  next_list_id,
  is_active,
  list_type,
  hidden_from_main_catalogue,
  primer_content
) values (
  'practice_most_common_people_and_family',
  'most-common-people-and-family',
  'practice',
  'Most Common People & Family',
  null,
  'Practise common Welsh words for people and family.',
  null,
  'Welsh',
  'en',
  'cy',
  'Mixed',
  'core',
  'topic-vocabulary',
  1,
  4,
  null,
  true,
  'main',
  false,
  '{
    "enabled": false,
    "titleEn": "",
    "titleCy": "",
    "bodyEn": "",
    "bodyCy": "",
    "soundItems": []
  }'::jsonb
) on conflict (id) do update set
  slug = excluded.slug,
  collection_id = excluded.collection_id,
  name = excluded.name,
  name_cy = excluded.name_cy,
  description = excluded.description,
  description_cy = excluded.description_cy,
  language = excluded.language,
  source_language = excluded.source_language,
  target_language = excluded.target_language,
  dialect = excluded.dialect,
  stage_id = excluded.stage_id,
  focus_category_id = excluded.focus_category_id,
  difficulty = excluded.difficulty,
  order_index = excluded.order_index,
  next_list_id = excluded.next_list_id,
  is_active = excluded.is_active,
  list_type = excluded.list_type,
  hidden_from_main_catalogue = excluded.hidden_from_main_catalogue,
  primer_content = excluded.primer_content;

insert into public.words (
  id,
  list_id,
  english_prompt,
  welsh_answer,
  accepted_alternatives,
  audio_url,
  audio_status,
  notes,
  usage_note,
  dialect,
  dialect_note,
  variant_group_id,
  order_index,
  difficulty
) values
  ('practice_most_common_people_and_family_001', 'practice_most_common_people_and_family', 'Mother', 'mam', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 1, 1),
  ('practice_most_common_people_and_family_002', 'practice_most_common_people_and_family', 'Father', 'tad', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 2, 1),
  ('practice_most_common_people_and_family_003', 'practice_most_common_people_and_family', 'Brother', 'brawd', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 3, 1),
  ('practice_most_common_people_and_family_004', 'practice_most_common_people_and_family', 'Sister', 'chwaer', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 4, 1),
  ('practice_most_common_people_and_family_005', 'practice_most_common_people_and_family', 'Friend', 'ffrind', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 5, 1),
  ('practice_most_common_people_and_family_006', 'practice_most_common_people_and_family', 'Child', 'plentyn', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 6, 1),
  ('practice_most_common_people_and_family_007', 'practice_most_common_people_and_family', 'Family', 'teulu', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 7, 1),
  ('practice_most_common_people_and_family_008', 'practice_most_common_people_and_family', 'Man', 'dyn', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 8, 1),
  ('practice_most_common_people_and_family_009', 'practice_most_common_people_and_family', 'Woman', 'dynes', '[]'::jsonb, '', 'missing', '', '', 'South Wales / Standard', 'North Wales commonly uses menyw.', 'woman', 9, 1),
  ('practice_most_common_people_and_family_010', 'practice_most_common_people_and_family', 'Woman', 'menyw', '[]'::jsonb, '', 'missing', '', '', 'North Wales', 'South/standard Welsh commonly uses dynes.', 'woman', 10, 1),
  ('practice_most_common_people_and_family_011', 'practice_most_common_people_and_family', 'Baby', 'babi', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 11, 1)
on conflict (id) do update set
  list_id = excluded.list_id,
  english_prompt = excluded.english_prompt,
  welsh_answer = excluded.welsh_answer,
  accepted_alternatives = excluded.accepted_alternatives,
  notes = excluded.notes,
  usage_note = excluded.usage_note,
  dialect = excluded.dialect,
  dialect_note = excluded.dialect_note,
  variant_group_id = excluded.variant_group_id,
  order_index = excluded.order_index,
  difficulty = excluded.difficulty;
