-- Adds hidden support-list audio records for Welsh Spelling Basics examples
-- that are not tied to a dedicated pattern practice list.

insert into public.word_lists (
  id,
  slug,
  collection_id,
  name,
  name_cy,
  description,
  description_cy,
  language,
  source_language,
  target_language,
  dialect,
  stage_id,
  focus_category_id,
  difficulty,
  order_index,
  next_list_id,
  is_active,
  list_type,
  hidden_from_main_catalogue
) values
  (
    'support_spelling_basics_examples',
    'support-spelling-basics-examples',
    'spelio_support_welsh',
    'Support: spelling basics examples',
    'Cymorth: enghreifftiau hanfodion sillafu',
    'Hidden support audio list for Welsh Spelling Basics explanatory examples.',
    'Rhestr sain gymorth gudd ar gyfer enghreifftiau esboniadol Hanfodion Sillafu Cymraeg.',
    'Welsh',
    'en',
    'cy',
    'Both',
    'support',
    'welsh-spelling-basics',
    1,
    10007,
    null,
    true,
    'support',
    true
  )
on conflict (id) do update set
  slug = excluded.slug,
  collection_id = excluded.collection_id,
  name = excluded.name,
  name_cy = excluded.name_cy,
  description = excluded.description,
  description_cy = excluded.description_cy,
  language = excluded.language,
  source_language = excluded.source_language,
  target_language = excluded.target_language,
  dialect = excluded.dialect,
  stage_id = excluded.stage_id,
  focus_category_id = excluded.focus_category_id,
  difficulty = excluded.difficulty,
  order_index = excluded.order_index,
  next_list_id = excluded.next_list_id,
  is_active = excluded.is_active,
  list_type = excluded.list_type,
  hidden_from_main_catalogue = excluded.hidden_from_main_catalogue;

insert into public.words (
  id,
  list_id,
  english_prompt,
  welsh_answer,
  accepted_alternatives,
  audio_url,
  audio_status,
  notes,
  usage_note,
  dialect,
  dialect_note,
  variant_group_id,
  order_index,
  difficulty
) values
  ('support_spelling_basics_examples_001', 'support_spelling_basics_examples', 'apple', 'afal', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 1, 1),
  ('support_spelling_basics_examples_002', 'support_spelling_basics_examples', 'old', 'hen', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 2, 1),
  ('support_spelling_basics_examples_003', 'support_spelling_basics_examples', 'you', 'ti', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 3, 1),
  ('support_spelling_basics_examples_004', 'support_spelling_basics_examples', 'morning', 'bore', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 4, 1),
  ('support_spelling_basics_examples_005', 'support_spelling_basics_examples', 'school', 'ysgol', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 5, 1),
  ('support_spelling_basics_examples_006', 'support_spelling_basics_examples', 'until', 'tan', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 6, 1)
on conflict (id) do update set
  list_id = excluded.list_id,
  english_prompt = excluded.english_prompt,
  welsh_answer = excluded.welsh_answer,
  accepted_alternatives = excluded.accepted_alternatives,
  notes = excluded.notes,
  usage_note = excluded.usage_note,
  dialect = excluded.dialect,
  dialect_note = excluded.dialect_note,
  variant_group_id = excluded.variant_group_id,
  order_index = excluded.order_index,
  difficulty = excluded.difficulty;
