insert into public.word_lists (
  id,
  slug,
  collection_id,
  name,
  name_cy,
  description,
  description_cy,
  language,
  source_language,
  target_language,
  dialect,
  stage_id,
  focus_category_id,
  difficulty,
  order_index,
  next_list_id,
  is_active,
  list_type,
  hidden_from_main_catalogue,
  primer_content
) values (
  'practice_most_common_clothing',
  'most-common-clothing',
  'practice',
  'Most Common Clothing',
  null,
  'Practise common Welsh clothing words used in everyday conversation.',
  null,
  'Welsh',
  'en',
  'cy',
  'Both',
  'core',
  'topic-vocabulary',
  1,
  7,
  null,
  true,
  'main',
  false,
  '{
    "enabled": false,
    "titleEn": "",
    "titleCy": "",
    "bodyEn": "",
    "bodyCy": "",
    "soundItems": []
  }'::jsonb
) on conflict (id) do update set
  slug = excluded.slug,
  collection_id = excluded.collection_id,
  name = excluded.name,
  name_cy = excluded.name_cy,
  description = excluded.description,
  description_cy = excluded.description_cy,
  language = excluded.language,
  source_language = excluded.source_language,
  target_language = excluded.target_language,
  dialect = excluded.dialect,
  stage_id = excluded.stage_id,
  focus_category_id = excluded.focus_category_id,
  difficulty = excluded.difficulty,
  order_index = excluded.order_index,
  next_list_id = excluded.next_list_id,
  is_active = excluded.is_active,
  list_type = excluded.list_type,
  hidden_from_main_catalogue = excluded.hidden_from_main_catalogue,
  primer_content = excluded.primer_content;

insert into public.words (
  id,
  list_id,
  english_prompt,
  welsh_answer,
  accepted_alternatives,
  audio_url,
  audio_status,
  notes,
  usage_note,
  dialect,
  dialect_note,
  variant_group_id,
  order_index,
  difficulty
) values
  ('practice_most_common_clothing_001', 'practice_most_common_clothing', 'Clothes', 'dillad', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 1, 1),
  ('practice_most_common_clothing_002', 'practice_most_common_clothing', 'Coat', 'cot', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 2, 1),
  ('practice_most_common_clothing_003', 'practice_most_common_clothing', 'Shoes', 'esgidiau', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 3, 1),
  ('practice_most_common_clothing_004', 'practice_most_common_clothing', 'Hat', 'het', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 4, 1),
  ('practice_most_common_clothing_005', 'practice_most_common_clothing', 'Shirt', 'crys', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 5, 1),
  ('practice_most_common_clothing_006', 'practice_most_common_clothing', 'Trousers', 'trowsus', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 6, 1),
  ('practice_most_common_clothing_007', 'practice_most_common_clothing', 'Dress', 'ffrog', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 7, 1),
  ('practice_most_common_clothing_008', 'practice_most_common_clothing', 'Sock', 'hosan', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 8, 1),
  ('practice_most_common_clothing_009', 'practice_most_common_clothing', 'Jumper', 'siwmper', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 9, 1),
  ('practice_most_common_clothing_010', 'practice_most_common_clothing', 'Jacket', 'siaced', '[]'::jsonb, '', 'missing', '', '', 'Both', '', '', 10, 1)
on conflict (id) do update set
  list_id = excluded.list_id,
  english_prompt = excluded.english_prompt,
  welsh_answer = excluded.welsh_answer,
  accepted_alternatives = excluded.accepted_alternatives,
  notes = excluded.notes,
  usage_note = excluded.usage_note,
  dialect = excluded.dialect,
  dialect_note = excluded.dialect_note,
  variant_group_id = excluded.variant_group_id,
  order_index = excluded.order_index,
  difficulty = excluded.difficulty;
